DROP TABLE IF EXISTS cdm.metrica_1;

CREATE TABLE cdm.metrica_1 (
bukrs VARCHAR(8) not null,
pyord VARCHAR(20) not null,
belnr bigint not null,
gjahr INTEGER not null,
hbkid VARCHAR(10) not null,
zbukr VARCHAR(10) not null,
butxt VARCHAR(50),
laufd TIMESTAMP(6),
text1 VARCHAR(80),
waers_b VARCHAR(20),
bankn VARCHAR(18),
rbetr FLOAT(4),
zz_bezakc VARCHAR(2),
zz_pyord_r VARCHAR(20),
zz_zh2h VARCHAR(2),
kblnr bigint,
waers_t VARCHAR(10),
zz_vblnr VARCHAR(20),
awkey VARCHAR(20),
zz_rfha VARCHAR(26),
partner VARCHAR(20),
name_first VARCHAR(80), 
namemiddle VARCHAR(80),  
name_last VARCHAR(80), 
zz_bukrs  VARCHAR(8),
zz_fdatk  DATE,
zz_hbkid  VARCHAR(10),
bkont VARCHAR(5),
zz_rfhazu INT,
zz_rfhazb INT,
zz_dcrdat DATE,
zz_tcrtim TIME(3),
wtges FLOAT,
banka VARCHAR(80),
CONSTRAINT pk_cdm_metrica_1 PRIMARY KEY (bukrs,pyord,belnr,gjahr,hbkid,zbukr)
);

DROP TABLE IF EXISTS cdm.metrica_2_3;

CREATE TABLE cdm.metrica_2_3(
bukrs VARCHAR(8) not null,
rfha bigint not null,
dcrdat DATE not null,
tcrtim TIME(3) not null,
zz_hbkid VARCHAR(10),
zuond VARCHAR(30),
banks VARCHAR(6),
zz_num_reg VARCHAR(50),
nordext VARCHAR(32),
sgsart VARCHAR(6),
sfhaart VARCHAR(6),
zz_bankname VARCHAR(120),
wgschft VARCHAR(20),
kontrh VARCHAR(20),
dbuchung DATE,
ssign VARCHAR(2),
bzbetr FLOAT(4),
dis_flowtype VARCHAR(8),
posting_key VARCHAR(2),
position_amt FLOAT(4),
position_curr VARCHAR(10),
sfhazba VARCHAR(8),
limit_date TIMESTAMP(6),
rfha_relat_obj VARCHAR(26),
limit_currency VARCHAR(10),
limit_pos_amount FLOAT(4),
rfhazu INT not null,
rfhazb INT not null,
dzterm DATE,
saktiv INT,
sbewebe VARCHAR(1),
acpostingdate DATE,
facilitynr Varchar(26),
name_org1 Varchar(80),
name_org2 Varchar(80),
name_org3 Varchar(80),
name_org4 Varchar(80),
sgsart_name Varchar(80),
CONSTRAINT pk_cdm_metrica_2_3 PRIMARY KEY (bukrs,rfha,dcrdat,tcrtim,limit_date,rfhazb,rfhazu)
);

DROP TABLE IF EXISTS cdm.metrica_4;

CREATE TABLE cdm.metrica_4(
bukrs VARCHAR(8) not null,
rfha bigint not null,
dcrdat DATE not null,
tcrtim TIME(3) not null,
zuond VARCHAR(30),
zz_num_reg VARCHAR(50),
kontrh VARCHAR(20),
butxt VARCHAR(50),
sgsart VARCHAR(6),
sfhaart VARCHAR(6),
wgschft VARCHAR(20),
ssign VARCHAR(2),
dzterm DATE,
bzbetr FLOAT(4),
rfhazu INT not null,
rfhazb INT not null,
zz_begda DATE,
sfhazba Varchar(8),
sbewebe Varchar(1),
dberbis date,
khwkurs Float,
dbervon date,
wzbetr Varchar(5),
name_org1 Varchar(80),
name_org2 Varchar(80),
name_org3 Varchar(80),
name_org4 Varchar(80),
CONSTRAINT pk_cdm_metrica_4 PRIMARY KEY (bukrs,rfha,dcrdat,tcrtim,rfhazu,rfhazb)
);